#!/usr/bin/env python3
"""Regenerate README.md and skills/<id>/README.md from sources.yml.

Everything this writes is derived. Edit sources.yml, then run:
    ./.venv/bin/python scripts/build.py
"""
from __future__ import annotations

import datetime as dt
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCES = ROOT / "sources.yml"
def esc(v) -> str:
    """Escape angle brackets so placeholders like <YYYY-MM> survive Markdown."""
    return str(v).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


GENERATED = "<!-- GENERATED BY scripts/build.py — DO NOT EDIT. Edit sources.yml instead. -->"

ORIGIN_LABEL = {
    "mosofin-workspace": "Mosofin workspace",
    "mosofin-published": "Mosofin published",
    "third-party": "Third party",
}

# Host capabilities a skill needs, inferred from its grading. See docs/TRUST-TIERS.md
# — these are stated inferences, not test results.
PLATFORMS = ["Claude Code", "Claude.ai", "Codex", "Cursor", "Gemini CLI", "Copilot"]
HOST_CAPS = {
    # platform: (runs scripts, persistent filesystem, MCP connectors)
    "Claude Code": (True, True, True),
    "Claude.ai": (True, False, True),
    "Codex": (True, True, False),
    "Cursor": (True, True, True),
    "Gemini CLI": (True, True, False),
    "Copilot": (False, False, False),
}


def needs(skill: dict) -> tuple[bool, bool, bool]:
    """(code execution, persistent filesystem, connector) — derived from grading."""
    tiers = set(skill.get("tiers") or [])
    inputs = skill.get("inputs") or []
    outputs = skill.get("outputs") or []
    code = bool(tiers & {"DETERMINISTIC-MATH", "TIE-CHECKED"})
    fs = bool(tiers & {"AUDIT-TRAIL", "STATEFUL", "POLICY-CAPTURING"}) or any(
        "workspace" in str(o.get("dest", "")) or "closes/" in str(o.get("dest", ""))
        for o in outputs
    )
    conn = any("integration manifest" in str(i.get("source", "")) for i in inputs)
    return code, fs, conn


def compat_row(skill: dict) -> str:
    if skill.get("status") == "UNGRADED":
        return " | ".join("?" for _ in PLATFORMS)
    n_code, n_fs, n_conn = needs(skill)
    cells = []
    for p in PLATFORMS:
        h_code, h_fs, h_conn = HOST_CAPS[p]
        missing = []
        if n_code and not h_code:
            missing.append("no scripts")
        if n_fs and not h_fs:
            missing.append("no workspace")
        if n_conn and not h_conn:
            missing.append("supply exports")
        cells.append("full" if not missing else "partial — " + ", ".join(missing))
    return " | ".join(cells)


def badges(skill: dict) -> str:
    out = [f"`{skill['status']}`"]
    out += [f"`{t}`" for t in (skill.get("tiers") or [])]
    return " ".join(out)


def is_stale(skill: dict, days: int) -> bool:
    lg = skill.get("last_graded")
    if not lg:
        return False
    return (dt.date.today() - dt.date.fromisoformat(str(lg))).days > days


def upstream_str(skill: dict) -> str:
    up = skill.get("upstream") or {}
    if "repo" in up:
        return (
            f"[`{up['repo']}/{up['path']}`]"
            f"(https://github.com/{up['repo']}/tree/{up.get('ref', 'main')}/{up['path']})"
        )
    return f"`{up.get('local', 'unknown')}` (local)"


def skill_page(skill: dict, meta: dict) -> str:
    L = [GENERATED, "", f"# {skill['title']}", "", badges(skill), "", skill["summary"].strip(), ""]

    L += ["| | |", "|---|---|"]
    L += [f"| Origin | {ORIGIN_LABEL.get(skill['origin'], skill['origin'])} |"]
    L += [f"| Stage | {skill['stage']} — {meta['stages'][skill['stage']]['name']} |"]
    L += [f"| Systems | {', '.join(skill.get('systems') or ['—'])} |"]
    L += [f"| Source | {upstream_str(skill)} |"]
    L += [f"| License | `{skill.get('license', 'unknown')}` |"]
    L += [f"| Mirrored here | {'yes' if skill.get('mirror') else 'no — pointer only'} |"]
    if skill.get("last_graded"):
        L += [f"| Last graded | {skill['last_graded']} |"]
    L += [""]

    if skill.get("status") == "UNGRADED":
        L += [
            "> **Not yet graded.** This entry is listed and pointed at, but nobody has read",
            "> its source line-by-line and assigned trust tiers. Treat the absence of badges",
            "> as *unknown*, not as *passing*. Inputs and outputs below are unverified.",
            "",
        ]

    if skill.get("tier_notes"):
        L += ["## Why these badges", ""]
        for tier, note in skill["tier_notes"].items():
            L += [f"- **`{tier}`** — {esc(note)}"]
        L += [""]

    if skill.get("inputs"):
        L += ["## Inputs", "", "| Input | Required | Where it comes from | If it's missing |", "|---|---|---|---|"]
        for i in skill["inputs"]:
            req = "**yes**" if i.get("required") else "no"
            L += [f"| `{esc(i['name'])}` | {req} | {esc(i.get('source', '—'))} | {esc(i.get('fallback', '—'))} |"]
        L += [""]

    if skill.get("outputs"):
        L += ["## Outputs", "", "| Output | Type | Where it lands |", "|---|---|---|"]
        for o in skill["outputs"]:
            L += [f"| {esc(o['name'])} | {esc(o.get('type', '—'))} | {esc(o.get('dest', '—'))} |"]
        L += [""]

    if skill.get("never"):
        L += ["## What it will not do", ""]
        L += [f"- {esc(n)}" for n in skill["never"]]
        L += [""]

    L += ["## Host compatibility", ""]
    L += ["| " + " | ".join(PLATFORMS) + " |", "|" + "---|" * len(PLATFORMS)]
    L += ["| " + compat_row(skill) + " |", ""]
    if skill.get("status") != "UNGRADED":
        n_code, n_fs, n_conn = needs(skill)
        req = [
            x
            for x, on in (
                ("script execution", n_code),
                ("a persistent workspace", n_fs),
                ("a live data connector", n_conn),
            )
            if on
        ]
        L += [f"Requires from the host: {', '.join(req) if req else 'nothing beyond reading instructions'}.", ""]
    L += [
        "*Inferred from the skill's grading, not from running it on each platform —"
        " see [Platform compatibility](../../docs/TRUST-TIERS.md#platform-compatibility).*",
        "",
        "---",
        "",
        "[← back to the index](../../README.md) · [trust tiers](../../docs/TRUST-TIERS.md)",
        "",
    ]
    return "\n".join(L)


def index_page(data: dict) -> str:
    meta = {**data["meta"], "stages": data["stages"]}
    skills = data["skills"]
    graded = [s for s in skills if s["status"] == "GRADED"]
    stale = [s for s in graded if is_stale(s, meta["regrade_after_days"])]
    regrade = [s for s in skills if s["status"] == "NEEDS-RE-GRADING"]
    # Derived from the data, never from wall-clock time: generated output must be
    # byte-identical on any day sources.yml has not changed, or CI's sync check
    # fails every day after the commit that produced it.
    checks = [str(s["last_checked"]) for s in skills if s.get("last_checked")]
    checked = max(checks) if checks else ""

    L = [GENERATED, "", f"# {meta['title']}", "", meta["tagline"], ""]
    L += [
        f"**{len(skills)} skills** · **{len(graded)} graded** · "
        f"**{len(skills) - len(graded)} awaiting grading** · "
        f"**{len(regrade)} need re-grading** · **{len(stale)} stale**"
        + (f" · pointers last checked {checked}" if checked else ""),
        "",
        "Every entry is graded for what happens when it is wrong: whether it can write to",
        "your ledger, whether its numbers are computed or asserted, whether it ends in a",
        "proof, and whether anything it produces can leave the building on its own.",
        "",
        "Other skill directories grade nothing. A skill that silently posts journal entries",
        "and one that proposes them look identical in a bullet list. In accounting they are",
        "not the same product.",
        "",
        "**[Read the trust tiers →](docs/TRUST-TIERS.md)**",
        "",
        "Nothing here is mirrored. Every third-party entry is a pointer to its own",
        "repository, checked daily; when an upstream `SKILL.md` changes, its grade is",
        "marked stale and a human re-reads it. The list is cheap — the grade is the product.",
        "",
        "---",
        "",
        "## The index",
        "",
        "Ordered by when you need it, not alphabetically.",
        "",
    ]

    for stage_no in sorted(meta["stages"]):
        stage = meta["stages"][stage_no]
        rows = [s for s in skills if s["stage"] == stage_no]
        if not rows:
            continue
        L += [f"### {stage_no} · {stage['name']}", "", f"*{stage['note']}*", ""]
        for s in sorted(rows, key=lambda x: (x["status"] != "GRADED", x["id"])):
            L += [
                f"- **[{s['title']}](skills/{s['id']}/README.md)** — "
                f"{ORIGIN_LABEL.get(s['origin'], s['origin'])}  "
            ]
            L += [f"  {badges(s)}  "]
            L += [f"  {' '.join(s['summary'].split())}"]
        L += [""]

    L += [
        "---",
        "",
        "## How this repository works",
        "",
        "```",
        "sources.yml              the only file you edit by hand",
        "scripts/build.py         regenerates README.md and skills/*/README.md",
        "scripts/check_drift.py   compares each pointer against upstream, daily in CI",
        "docs/TRUST-TIERS.md      what every badge means",
        "skills/<id>/README.md    generated — purpose, inputs, outputs, limits",
        "```",
        "",
        "```bash",
        "python3 -m venv .venv && ./.venv/bin/pip install -r requirements.txt",
        "./.venv/bin/python scripts/build.py",
        "```",
        "",
        "## Licensing and why nothing is vendored",
        "",
        "`anthropics/skills` ships a per-skill `LICENSE.txt` reading *\"© 2025 Anthropic, PBC.",
        "All rights reserved\"*, with use governed by your own Anthropic agreement. That is not",
        "an open-source licence, so those skills are **pointed at, never copied**. CI fails any",
        "pull request that adds files under a pointer whose licence is not permissive.",
        "",
        "The published Mosofin skills are AGPL-3.0 — open source, but strong copyleft. They are",
        "pointed at rather than vendored, because mirroring them would relicense this index.",
        "That is a decision to take on purpose, not by default.",
        "",
        "Entries carrying a permissive licence (MIT, Apache-2.0) may set `mirror: true` and be",
        "vendored under `vendor/`, with attribution generated into `THIRD_PARTY_NOTICES.md`.",
        "",
        "## Contributing",
        "",
        "See [CONTRIBUTING.md](CONTRIBUTING.md). Adding an entry means adding a block to",
        "`sources.yml` and running the build — never editing a generated file.",
        "",
    ]
    return "\n".join(L)


def main() -> int:
    data = yaml.safe_load(SOURCES.read_text())
    meta = {**data["meta"], "stages": data["stages"]}
    ids = [s["id"] for s in data["skills"]]
    if len(ids) != len(set(ids)):
        dupes = {i for i in ids if ids.count(i) > 1}
        print(f"duplicate ids in sources.yml: {sorted(dupes)}", file=sys.stderr)
        return 1

    (ROOT / "README.md").write_text(index_page(data))
    for skill in data["skills"]:
        d = ROOT / "skills" / skill["id"]
        d.mkdir(parents=True, exist_ok=True)
        (d / "README.md").write_text(skill_page(skill, meta))

    print(f"built README.md and {len(data['skills'])} skill pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
