#!/usr/bin/env python3
"""Generate the Claude plugin's reference files from the index.

The plugin is the directory-publishable face of this repository. It ships one
read-only skill, `finance-ops-skills`, plus a generated reference file per vendor.
Nothing from a vendor is copied: each entry is a pointer to the upstream skill.

Called from build.py. Everything under plugins/<name>/skills/*/references/ and the
plugin README is derived; plugin.json, the SKILL.md and LICENSE are hand-written.
"""
from __future__ import annotations

import pathlib
import shutil

PLUGIN = "finance-ops-skills-index"
SKIP_STATUS = {"local"}
GENERATED = "<!-- GENERATED BY scripts/build_plugin.py — DO NOT EDIT. Edit data/ and connectors.yml. -->"


def _link(skill: dict) -> str:
    up = skill.get("upstream") or {}
    if "repo" not in up:
        return f"`{up.get('local', 'unknown')}` (local)"
    return f"https://github.com/{up['repo']}/tree/{up.get('ref', 'main')}/{up['path']}"


def _vendor_page(cid: str, c: dict, skills: list, statuses: dict) -> str:
    repo = c.get("skills_repo", "none")
    L = [GENERATED, "", f"# {cid}", ""]
    L.append(f"- Reachability: **{c['status']}** — {statuses.get(c['status'], '')}")
    L.append(f"- Vertical: {c.get('vertical', 'n/a')}")
    if repo and repo != "none":
        L.append(f"- Vendor skills repository: https://github.com/{repo}")
        L.append(
            f"- Published there: {c.get('skills_published', 0)} · "
            f"indexed here: {len(skills)} · checked {c.get('skills_checked', 'n/a')}"
        )
        if c.get("skills_license"):
            L.append(f"- Repository licence: {c['skills_license']}")
        if c.get("skills_note"):
            L.append(f"- Note: {' '.join(str(c['skills_note']).split())}")
    else:
        L.append(
            f"- **No vendor-published skills found** as of {c.get('skills_checked', 'the last check')}."
        )
    L += ["", "## Indexed skills", ""]
    if not skills:
        L.append("None indexed. Do not invent one — say so and point to the vendor's own developer docs.")
    for s in sorted(skills, key=lambda x: x["id"]):
        L += [
            f"### {s['id']}",
            "",
            f"- Authority: {s.get('authority', 'community')} · stage {s.get('stage', 'n/a')} · "
            f"status {s.get('status', 'UNGRADED')}"
            + (f" (graded {s['last_graded']})" if s.get("last_graded") else ""),
            f"- Trust badges: {', '.join(s.get('tiers') or []) or 'none'}",
            f"- Licence: {s.get('license', 'unknown')}",
            f"- Upstream: {_link(s)}",
            f"- Summary: {' '.join(str(s.get('summary', '')).split())}",
        ]
        if s.get("never"):
            L.append("- Never: " + " | ".join(str(n) for n in s["never"]))
        L.append("")
    return "\n".join(L)


def build(root: pathlib.Path, skills: list, connectors: dict, statuses: dict, primary_system) -> int:
    pdir = root / "plugins" / PLUGIN
    ref = pdir / "skills" / "finance-ops-skills" / "references"
    if ref.exists():
        shutil.rmtree(ref)
    ref.mkdir(parents=True)

    by_system: dict[str, list] = {}
    for s in skills:
        by_system.setdefault(primary_system(s), []).append(s)

    rows, n = [], 0
    for cid, c in connectors.items():
        if c.get("status") in SKIP_STATUS:
            continue
        mine = by_system.get(cid, [])
        (ref / f"{cid}.md").write_text(_vendor_page(cid, c, mine, statuses))
        repo = c.get("skills_repo", "none")
        rows.append(
            f"| {cid} | {c.get('vertical', '')} | {c['status']} | "
            f"{'none' if repo in (None, 'none') else repo} | {len(mine)} |"
        )
        n += 1

    anyskills = by_system.get("_any", [])
    (ref / "_any.md").write_text(
        _vendor_page("_any (no connected system)", {"status": "local", "vertical": "files"}, anyskills, statuses)
    )

    (ref / "INDEX.md").write_text(
        "\n".join(
            [GENERATED, "", "# Vendors in this index", "",
             "| Vendor | Vertical | Reachability | Vendor skills repo | Indexed |",
             "| - | - | - | - | - |", *rows,
             f"| _any | files | local | — | {len(anyskills)} |", ""]
        )
    )

    (pdir / "README.md").write_text(
        "\n".join(
            [
                GENERATED, "",
                "# Finance & ops skills index", "",
                "A Claude plugin that helps Claude find agent skills published by the vendors behind "
                "finance and business-operations software, such as accounting, payments and e-commerce "
                "platforms. It carries a read-only catalog of pointers: for each vendor it records "
                "where the skills live upstream, who published them, their licence, and an independent "
                "grade for write authority and verification.", "",
                "## What it does", "",
                "Ask Claude things like \"are there skills for Xero?\" or \"which QuickBooks skills can "
                "post journal entries?\". The bundled `finance-ops-skills` skill reads the catalog and "
                "answers with the upstream link, the publisher, the trust badges and whether the "
                "vendor's data can actually be reached.", "",
                "## What it does not do", "",
                "- It does not copy, install or run any vendor skill; every entry links to the "
                "publisher's own repository.",
                "- It makes no network calls, runs no scripts and holds no credentials.",
                "- It does not connect to any vendor account.", "",
                f"## Coverage ({n} vendors)", "",
                "See `skills/finance-ops-skills/references/INDEX.md` for the full table.", "",
                "## Source", "",
                "The catalog is generated from the data files in the repository root. "
                "Run `make build` to regenerate it.", "",
            ]
        )
    )
    return n
