#!/usr/bin/env python3
"""Regenerate every published page from data/ and connectors.yml.

Everything this writes is derived. Edit the data files, then run:
    ./.venv/bin/python scripts/build.py
"""
from __future__ import annotations

import datetime as dt
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
CONNECTORS = ROOT / "connectors.yml"

# Formats a user hands over, not systems we connect to.
FILE_FORMATS = {"csv", "pdf", "word", "powerpoint", "images", "any", "excel"}
AGNOSTIC = "_any"


def primary_system(skill: dict) -> str:
    real = [x for x in (skill.get("systems") or []) if x not in FILE_FORMATS]
    return real[0] if real else AGNOSTIC


def known_tiers() -> set[str]:
    """Badges defined in docs/TRUST-TIERS.md, so none can be invented in passing."""
    import re as _re
    text = (ROOT / "docs" / "TRUST-TIERS.md").read_text()
    return set(_re.findall(r"^\| `([A-Z][A-Z-]+)` \|", text, _re.M))


def load_index() -> dict:
    """Skills live under the data source they read: data/sources/<system>/<id>.yml."""
    meta = yaml.safe_load((DATA / "meta.yml").read_text())
    skills, misfiled = [], []
    for f in sorted((DATA / "sources").glob("*/*.yml")):
        sk = yaml.safe_load(f.read_text())
        if f.parent.name != primary_system(sk):
            misfiled.append(f"{f.relative_to(ROOT)} -> belongs in {primary_system(sk)}/")
        skills.append(sk)
    if misfiled:
        raise SystemExit("skills filed under the wrong data source:\n  " + "\n  ".join(misfiled))

    outward = [
        sk["id"] for sk in skills
        if "CLIENT-FACING" in (sk.get("tiers") or [])
        and not {"NO-AUTO-SEND", "SENDS-EXTERNALLY"} & set(sk.get("tiers") or [])
    ]
    if outward:
        raise SystemExit(
            "CLIENT-FACING without a send declaration: " + ", ".join(outward)
            + "\nA reader must never have to guess whether output leaves the building."
        )

    defined = known_tiers()
    unknown = sorted(
        {t for sk in skills for t in (sk.get("tiers") or [])} - defined
    )
    if unknown:
        raise SystemExit(
            "badges not defined in docs/TRUST-TIERS.md: " + ", ".join(unknown)
            + "\nA badge is a claim readers rely on — define it before using it."
        )
    return {**meta, "skills": skills}
def esc(v) -> str:
    """Escape angle brackets so placeholders like <YYYY-MM> survive Markdown."""
    return str(v).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


GENERATED = (
    "<!-- GENERATED BY scripts/build.py — DO NOT EDIT."
    " Edit data/sources/<system>/<id>.yml instead. -->"
)

AUTHORITY_LABEL = {
    "first-party": "**First-party** — published by the organisation that owns the product",
    "notable": "Notable — a widely-used author, but not the product owner",
    "community": "Community",
}

ORIGIN_LABEL = {
    "mosofin-workspace": "Mosofin workspace",
    "mosofin-published": "Mosofin published",
    "third-party": "Third party",
}

# Host capabilities a skill needs, inferred from its grading. See docs/TRUST-TIERS.md
# — these are stated inferences, not test results.
PERMISSIVE = {"mit", "apache-2.0", "bsd-3-clause", "bsd-2-clause", "isc", "cc0-1.0"}
COPYLEFT = {"agpl-3.0", "gpl-3.0", "gpl-2.0", "lgpl-3.0", "mpl-2.0"}

PLATFORMS = ["Claude Code", "Claude.ai", "Codex", "Cursor", "Gemini CLI", "Copilot"]
HOST_CAPS = {
    # platform: (runs scripts, persistent filesystem, MCP connectors)
    "Claude Code": (True, True, True),
    "Claude.ai": (True, False, True),
    "Codex": (True, True, False),
    "Cursor": (True, True, True),
    "Gemini CLI": (True, True, False),
    "Copilot": (False, False, False),
}


def needs(skill: dict) -> tuple[bool, bool, bool]:
    """(code execution, persistent filesystem, connector) — derived from grading."""
    tiers = set(skill.get("tiers") or [])
    inputs = skill.get("inputs") or []
    outputs = skill.get("outputs") or []
    code = bool(tiers & {"DETERMINISTIC-MATH", "TIE-CHECKED"})
    fs = bool(tiers & {"AUDIT-TRAIL", "STATEFUL", "POLICY-CAPTURING"}) or any(
        "workspace" in str(o.get("dest", "")) or "closes/" in str(o.get("dest", ""))
        for o in outputs
    )
    conn = any("integration manifest" in str(i.get("source", "")) for i in inputs)
    return code, fs, conn


def compat_row(skill: dict) -> str:
    if skill.get("status") == "UNGRADED":
        return " | ".join("?" for _ in PLATFORMS)
    n_code, n_fs, n_conn = needs(skill)
    cells = []
    for p in PLATFORMS:
        h_code, h_fs, h_conn = HOST_CAPS[p]
        missing = []
        if n_code and not h_code:
            missing.append("no scripts")
        if n_fs and not h_fs:
            missing.append("no workspace")
        if n_conn and not h_conn:
            missing.append("supply exports")
        cells.append("full" if not missing else "partial — " + ", ".join(missing))
    return " | ".join(cells)


def badges(skill: dict) -> str:
    out = [f"`{skill['status']}`"]
    out += [f"`{t}`" for t in (skill.get("tiers") or [])]
    return " ".join(out)


def is_stale(skill: dict, days: int) -> bool:
    lg = skill.get("last_graded")
    if not lg:
        return False
    return (dt.date.today() - dt.date.fromisoformat(str(lg))).days > days


def upstream_str(skill: dict) -> str:
    up = skill.get("upstream") or {}
    if "repo" in up:
        return (
            f"[`{up['repo']}/{up['path']}`]"
            f"(https://github.com/{up['repo']}/tree/{up.get('ref', 'main')}/{up['path']})"
        )
    return f"`{up.get('local', 'unknown')}` (local)"


def skill_page(skill: dict, meta: dict) -> str:
    L = [GENERATED, "", f"# {skill['title']}", "", badges(skill), "", skill["summary"].strip(), ""]

    L += ["| | |", "|---|---|"]
    L += [f"| Origin | {ORIGIN_LABEL.get(skill['origin'], skill['origin'])} |"]
    L += [f"| Authority | {AUTHORITY_LABEL.get(skill.get('authority', 'community'))} |"]
    L += [f"| Stage | {skill['stage']} — {meta['stages'][skill['stage']]['name']} |"]
    L += [f"| Systems | {', '.join(skill.get('systems') or ['—'])} |"]
    L += [f"| Source | {upstream_str(skill)} |"]
    L += [f"| License | `{skill.get('license', 'unknown')}` |"]
    L += [f"| Mirrored here | {'yes' if skill.get('mirror') else 'no — pointer only'} |"]
    if skill.get("last_graded"):
        L += [f"| Last graded | {skill['last_graded']} |"]
    L += [""]

    if skill.get("status") == "UNGRADED":
        L += [
            "> **Not yet graded.** This entry is listed and pointed at, but nobody has read",
            "> its source line-by-line and assigned trust tiers. Treat the absence of badges",
            "> as *unknown*, not as *passing*. Inputs and outputs below are unverified.",
            "",
        ]

    if skill.get("tier_notes"):
        L += ["## Why these badges", ""]
        for tier, note in skill["tier_notes"].items():
            L += [f"- **`{tier}`** — {esc(note)}"]
        L += [""]

    if skill.get("inputs"):
        L += ["## Inputs", "", "| Input | Required | Where it comes from | If it's missing |", "|---|---|---|---|"]
        for i in skill["inputs"]:
            req = "**yes**" if i.get("required") else "no"
            L += [f"| `{esc(i['name'])}` | {req} | {esc(i.get('source', '—'))} | {esc(i.get('fallback', '—'))} |"]
        L += [""]

    if skill.get("outputs"):
        L += ["## Outputs", "", "| Output | Type | Where it lands |", "|---|---|---|"]
        for o in skill["outputs"]:
            L += [f"| {esc(o['name'])} | {esc(o.get('type', '—'))} | {esc(o.get('dest', '—'))} |"]
        L += [""]

    if skill.get("never"):
        L += ["## What it will not do", ""]
        L += [f"- {esc(n)}" for n in skill["never"]]
        L += [""]

    conn = meta.get("connectors", {})
    cstat = meta.get("statuses", {})
    rows = [(sys_, conn.get(sys_, {})) for sys_ in (skill.get("systems") or [])]
    if rows:
        L += ["## Data reachability", "", "| System | Status | Auth | Settlement data |", "|---|---|---|---|"]
        for name, c in rows:
            st = c.get("status", "unknown")
            L += [
                f"| `{name}` | **{st}** — {cstat.get(st, '')} | `{c.get('auth', '—')}` "
                f"| {c.get('payouts', '—')} |"
            ]
        L += [""]
        blocked = [n for n, c in rows if c.get("status") in {"gated", "declined"}]
        costly = [n for n, c in rows if c.get("status") == "hard"]
        if blocked:
            L += [f"> **Not reachable.** {', '.join(blocked)} — the grading above is academic until that changes.", ""]
        elif costly:
            L += [f"> **Reachable at cost.** {', '.join(costly)} needs per-merchant credentials or a plan upgrade.", ""]
        notes = [f"- `{n}` — {c['note']}" for n, c in rows if c.get("note")]
        if notes:
            L += notes + [""]

    L += ["## Host compatibility", ""]
    L += ["| " + " | ".join(PLATFORMS) + " |", "|" + "---|" * len(PLATFORMS)]
    L += ["| " + compat_row(skill) + " |", ""]
    if skill.get("status") != "UNGRADED":
        n_code, n_fs, n_conn = needs(skill)
        req = [
            x
            for x, on in (
                ("script execution", n_code),
                ("a persistent workspace", n_fs),
                ("a live data connector", n_conn),
            )
            if on
        ]
        L += [f"Requires from the host: {', '.join(req) if req else 'nothing beyond reading instructions'}.", ""]
    L += [
        "*Inferred from the skill's grading, not from running it on each platform —"
        " see [Platform compatibility](../../docs/TRUST-TIERS.md#platform-compatibility).*",
        "",
        "---",
        "",
        "[← back to the index](../../README.md) · [trust tiers](../../docs/TRUST-TIERS.md)",
        "",
    ]
    return "\n".join(L)


STATUS_ORDER = [
    "live", "code-complete", "roadmap", "candidate",
    "costly", "gated", "not-recommended", "declined", "local",
]


def connector_section(conn: dict) -> list[str]:
    """The candidate list, grouped by how committed each connector is."""
    cs, out = conn["statuses"], []
    by_status: dict[str, list] = {}
    for name, c in conn["connectors"].items():
        by_status.setdefault(c.get("status", "candidate"), []).append((name, c))

    for status in STATUS_ORDER:
        rows = sorted(by_status.get(status, []))
        if not rows or status == "local":
            continue
        out += [
            f"#### {status} — {cs.get(status, '')}",
            "",
            "| Connector | Family | Auth | Entity | Token | Settlement | Lead time |",
            "|---|---|---|---|---|---|---|",
        ]
        for name, c in rows:
            key = c.get("connector_key")
            label = f"`{name}`" + (f"<br><sub>`{key}`</sub>" if key else "")
            out.append(
                f"| {label} | {c.get('family', '—')} | `{c.get('auth', '—')}` "
                f"| {esc(c.get('entity', '—'))} | {esc(c.get('token', '—'))} "
                f"| {c.get('payouts', '—')} | {esc(c.get('lead_time', '—'))} |"
            )
        out.append("")
        notes = [(n, c["note"]) for n, c in rows if c.get("note")]
        for n, note in notes:
            out.append(f"- **`{n}`** — {esc(' '.join(note.split()))}")
        if notes:
            out.append("")
    return out


def publisher_rows(skills: list) -> list[str]:
    """One row per upstream publisher, so provenance is visible at a glance."""
    groups: dict[str, dict] = {}
    for s in skills:
        up = s.get("upstream") or {}
        key = up.get("repo") or "Mosofin (local workspace)"
        g = groups.setdefault(key, {"n": 0, "auth": set(), "lic": set()})
        g["n"] += 1
        g["auth"].add(s.get("authority", "community"))
        g["lic"].add(str(s.get("license", "unknown")))

    rows = []
    for repo, g in sorted(groups.items(), key=lambda kv: (-kv[1]["n"], kv[0])):
        name = (
            f"[`{repo}`](https://github.com/{repo})" if "/" in repo and " " not in repo else repo
        )
        lic = ", ".join(sorted(g["lic"]))
        vendorable = (
            "yes"
            if all(l in PERMISSIVE for l in g["lic"])
            else ("no — copyleft" if any(l in COPYLEFT for l in g["lic"]) else "no — restricted")
        )
        rows.append(
            f"| {name} | {g['n']} | {', '.join(sorted(g['auth']))} | `{lic}` | {vendorable} |"
        )
    return rows


# File formats are not data sources; they get no page.
NOT_A_SOURCE = {"csv", "pdf", "word", "powerpoint", "images", "any"}


def connector_page(cid: str, c: dict, conn: dict, skills: list, stages: dict) -> str:
    """One page per data source: how to reach it, and what runs once you have."""
    cs = conn["statuses"]
    users = [s for s in skills if cid in (s.get("systems") or [])]

    L = [GENERATED, "", f"# {cid}", "",
         f"`{c.get('status')}` `family-{c.get('family', 'none')}` `{c.get('auth', '—')}`", ""]
    L += [f"**{cs.get(c.get('status'), '')}**", ""]

    L += ["| | |", "|---|---|"]
    rows = [
        ("Status", f"{c.get('status')} — {cs.get(c.get('status'), '')}"),
        ("connector_key", f"`{c['connector_key']}`" if c.get("connector_key") else None),
        ("Family", c.get("family")),
        ("Auth model", f"`{c.get('auth')}` — {conn['auth_models'].get(c.get('auth'), '')}"),
        ("Entity", c.get("entity")),
        ("Token", c.get("token")),
        ("Lead time", c.get("lead_time")),
        ("Settlement data", c.get("payouts")),
        ("Vertical", c.get("vertical")),
        ("Assessed in", c.get("source")),
    ]
    for k, v in rows:
        if v:
            L.append(f"| {k} | {esc(v)} |")
    L += [""]

    if c.get("note"):
        L += ["## What to watch", "", esc(" ".join(c["note"].split())), ""]

    repo = c.get("skills_repo")
    L += ["## Official skills from the vendor", ""]
    if repo and repo != "none":
        L += [f"[`{repo}`](https://github.com/{repo}) · licence `{c.get('skills_license', '?')}` "
              f"· probed {c.get('skills_checked', '—')}", "",
              f"- **{c.get('skills_published', 0)}** skills published",
              f"- **{c.get('skills_relevant', 0)}** finance-relevant",
              f"- **{c.get('skills_indexed', 0)}** indexed here", ""]
        if c.get("skills_note"):
            L += [esc(" ".join(c["skills_note"].split())), ""]
    elif c.get("github_org") == "none-found":
        L += ["No public GitHub organisation at the obvious name. Not probed further.", ""]
    else:
        org = c.get("github_org")
        L += [f"None. [`{org}`](https://github.com/{org}) was probed on "
              f"{c.get('skills_checked', '—')} and publishes no agent skills — a dated fact, "
              f"not a permanent state.", ""]

    L += ["## Skills in this index that need it", ""]
    if users:
        by_stage: dict = {}
        for sk in users:
            by_stage.setdefault(sk["stage"], []).append(sk)
        for st in sorted(by_stage):
            L += [f"**{st} · {stages[st]['name']}**", ""]
            for sk in sorted(by_stage[st], key=lambda x: x["id"]):
                L.append(f"- [{sk['title']}](../../skills/{sk['id']}/README.md) — "
                         f"`{sk['status']}`" +
                         ("".join(f" `{t}`" for t in (sk.get("tiers") or []))))
            L.append("")
    else:
        L += ["None yet. Connecting this reaches data no indexed skill currently reads.", ""]

    L += ["---", "", "[← all connectors](../README.md) · "
          "[the index](../../README.md) · [tracker](../../docs/CONNECTOR-TRACKER.md)", ""]
    return "\n".join(L)


def connectors_index(conn: dict, skills: list) -> str:
    """Directory page for connectors/."""
    cs = conn["statuses"]
    L = [GENERATED, "", "# Data sources", "",
         "One page per system Mosofin connects or has assessed — how to reach it, what it",
         "costs to reach, whether its vendor publishes skills, and which skills in this",
         "index run once it is connected.", ""]
    for status in STATUS_ORDER:
        rows = sorted((n, c) for n, c in conn["connectors"].items()
                      if c.get("status") == status and n not in NOT_A_SOURCE)
        if not rows:
            continue
        L += [f"## {status} — {cs.get(status, '')}", ""]
        for n, c in rows:
            used = sum(1 for s in skills if n in (s.get("systems") or []))
            bits = [f"`{c.get('auth', '—')}`"]
            if c.get("lead_time"):
                bits.append(esc(c["lead_time"]))
            bits.append(f"{used} skill{'s' if used != 1 else ''} in this index")
            L.append(f"- **[{n}]({n}/README.md)** — " + " · ".join(bits))
        L += [""]
    L += ["---", "", "[← the index](../README.md)", ""]
    return "\n".join(L)


def tracker_page(conn: dict) -> str:
    """Vendor by vendor: does this connector's owner publish agent skills?

    Grouped by repository, not by connector — three Workspace connectors share
    one repo, and counting it three times would overstate both the total and
    the gap.
    """
    rows = [(n, c) for n, c in conn["connectors"].items() if c.get("github_org")]
    repos: dict[str, dict] = {}
    for n, c in rows:
        r = c.get("skills_repo")
        if r in (None, "none"):
            continue
        g = repos.setdefault(r, {"connectors": [], "c": c})
        g["connectors"].append(n)
    none_yet = [(n, c) for n, c in rows if c.get("skills_repo") in (None, "none")]

    def relevant(g):
        return sum(conn["connectors"][n].get("skills_relevant", 0) for n in g["connectors"])

    published = sum(g["c"].get("skills_published", 0) for g in repos.values())
    rel_total = sum(relevant(g) for g in repos.values())
    gap = {r: g for r, g in repos.items() if relevant(g) > g["c"].get("skills_indexed", 0)}

    L = [GENERATED, "", "# Connector Tracker", "",
         "For every connector on the roadmap: who owns it on GitHub, whether they publish",
         "agent skills of their own, and how many this index carries.", "",
         f"**{len(rows)} connectors tracked** · **{len(repos)} vendor skill repositories** · "
         f"**{published} skills published** · **{rel_total} finance-relevant** · "
         f"**{len(none_yet)} vendors publish none**", "",
         "*Published* is everything in the repo. *Relevant* is what belongs in a finance",
         "index — most vendor skills teach you to build on their platform, which is a",
         "different job. The difference is triage, not backlog; the notes say what was left",
         "out and why.", "",
         "Refresh with `make probe`. A vendor publishing nothing today is a fact with a date",
         "on it, not a permanent state.", "",
         "## Vendors that publish agent skills", "",
         "| Repository | Serves | Published | Relevant | Indexed | Licence | Checked |",
         "|---|---|---|---|---|---|---|"]
    for r, g in sorted(repos.items(), key=lambda kv: -relevant(kv[1])):
        c = g["c"]
        L.append(
            f"| [`{r}`](https://github.com/{r}) | {', '.join(f'`{x}`' for x in sorted(g['connectors']))} "
            f"| {c.get('skills_published', 0)} | {relevant(g)} | {c.get('skills_indexed', 0)} "
            f"| `{c.get('skills_license', '?')}` | {c.get('skills_checked', '—')} |"
        )
    L += [""]
    for r, g in sorted(repos.items()):
        # dict.fromkeys, not a set: set iteration order varies with PYTHONHASHSEED,
        # which makes generated output differ between runs and breaks the CI sync check.
        notes = dict.fromkeys(
            conn["connectors"][n].get("skills_note") for n in sorted(g["connectors"])
        )
        for note in filter(None, notes):
            L.append(f"- **[`{r}`](https://github.com/{r})** — {esc(' '.join(note.split()))}")
    L += ["", "## Vendors that publish none", "",
          "Org exists and was probed; no `SKILL.md` in any repo whose name suggests agents,",
          "skills, MCP, a toolkit, a plugin, a CLI or an SDK.", "",
          "| Connector | Status | GitHub org | Checked |", "|---|---|---|---|"]
    for n, c in sorted(none_yet, key=lambda kv: (STATUS_ORDER.index(kv[1].get("status", "candidate")), kv[0])):
        org = c["github_org"]
        link = (f"[`{org}`](https://github.com/{org})" if org != "none-found"
                else "*no public org at the obvious name*")
        L.append(f"| `{n}` | {c.get('status')} | {link} | {c.get('skills_checked', '—')} |")

    L += ["", "## Relevant but not yet indexed", ""]
    if gap:
        for r, g in sorted(gap.items()):
            L.append(f"- **[`{r}`](https://github.com/{r})** — "
                     f"{relevant(g) - g['c'].get('skills_indexed', 0)} still to add")
    else:
        L.append("Nothing outstanding. Every finance-relevant vendor skill found is indexed.")
    L += ["", "---", "", "[← back to the index](../README.md)", ""]
    return "\n".join(L)


def index_page(data: dict, conn_meta: dict) -> str:
    meta = {**data["meta"], "stages": data["stages"]}
    skills = data["skills"]
    graded = [s for s in skills if s["status"] == "GRADED"]
    stale = [s for s in graded if is_stale(s, meta["regrade_after_days"])]
    regrade = [s for s in skills if s["status"] == "NEEDS-RE-GRADING"]
    # Derived from the data, never from wall-clock time: generated output must be
    # byte-identical on any day the data files have not changed, or CI's sync check
    # fails every day after the commit that produced it.
    checks = [str(s["last_checked"]) for s in skills if s.get("last_checked")]
    checked = max(checks) if checks else ""

    L = [GENERATED, "", f"# {meta['title']}", "", meta["tagline"], ""]
    L += [
        f"**{len(skills)} skills** · **{len(graded)} graded** · "
        f"**{len(skills) - len(graded)} awaiting grading** · "
        f"**{len(regrade)} need re-grading** · **{len(stale)} stale**"
        + (f" · pointers last checked {checked}" if checked else ""),
        "",
        "Every entry is graded for what happens when it is wrong: whether it can write to",
        "your ledger, whether its numbers are computed or asserted, whether it ends in a",
        "proof, and whether anything it produces can leave the building on its own.",
        "",
        "Other skill directories grade nothing. A skill that silently posts journal entries",
        "and one that proposes them look identical in a bullet list. In accounting they are",
        "not the same product.",
        "",
        "**[Read the trust tiers →](docs/TRUST-TIERS.md)**",
        "",
        "Nothing here is mirrored. Every third-party entry is a pointer to its own",
        "repository, checked daily; when an upstream `SKILL.md` changes, its grade is",
        "marked stale and a human re-reads it. The list is cheap — the grade is the product.",
        "",
        "---",
        "",
        "## The index",
        "",
        "Ordered by when you need it, not alphabetically.",
        "",
    ]

    for stage_no in sorted(meta["stages"]):
        stage = meta["stages"][stage_no]
        rows = [s for s in skills if s["stage"] == stage_no]
        if not rows:
            continue
        L += [f"### {stage_no} · {stage['name']}", "", f"*{stage['note']}*", ""]
        for s in sorted(rows, key=lambda x: (x["status"] != "GRADED", x["id"])):
            L += [
                f"- **[{s['title']}](skills/{s['id']}/README.md)** — "
                f"{ORIGIN_LABEL.get(s['origin'], s['origin'])}  "
            ]
            L += [f"  {badges(s)}  "]
            L += [f"  {' '.join(s['summary'].split())}"]
        L += [""]

    L += [
        "---",
        "",
        "## Connector pipeline",
        "",
        "One page per data source in **[connectors/](connectors/README.md)** — how to reach",
        "it, what it costs to reach, and which skills here run once it is connected.",
        "",
        "A grade says what a skill does when it runs. This says whether it can run at all.",
        "A perfectly graded reconciliation skill is inert when its ledger sits behind a",
        "partner gate, so reachability is stated beside the grade rather than left for the",
        "reader to discover.",
        "",
        *connector_section(conn_meta),
        f"Sources: [{conn_meta['meta']['sources']['runbook']['title']}]"
        f"({conn_meta['meta']['sources']['runbook']['url']}) "
        f"(verified {conn_meta['meta']['sources']['runbook']['verified']}) — the committed",
        "roadmap, with connector keys, entities and token strategies; and",
        f"[{conn_meta['meta']['sources']['survey']['title']}]"
        f"({conn_meta['meta']['sources']['survey']['url']}) "
        f"(researched {conn_meta['meta']['sources']['survey']['verified']}) — the evaluated",
        "pool. " + " ".join(conn_meta["meta"]["caveat"].split()),
        "",
        "Three facts from that survey shape this index more than any other:",
        "",
        "- **Who issues the credential decides everything.** Three-legged OAuth is a",
        "  connector; merchant-generated keys are a support burden; a partner agreement is",
        "  business development. Nothing about the API surface changes that ordering.",
        "- **An API without settlement data cannot close the books.** Reconciliation needs",
        "  payouts, not just sales.",
        "- **The processor is the escape hatch — except in field service**, where embedded",
        "  payments mean the platform API is the only path to the money.",
        "",
        "---",
        "",
        "## Publishers",
        "",
        "Who stands behind each entry. **First-party** means the organisation that owns the",
        "product published the skill itself — the standing `anthropics/skills` has for Claude.",
        "It is a statement about provenance, not about quality, and it is never a substitute",
        "for a grade.",
        "",
        "| Publisher | Entries | Authority | Licence | Vendorable |",
        "|---|---|---|---|---|",
        *publisher_rows(skills),
        "",
        "Eleven of the connectors above have owners who publish agent skills themselves —",
        "Intuit, Stripe, Shopify, PayPal, HubSpot, WooCommerce, Amazon, Google and Microsoft",
        "among them. **[Connector Tracker](docs/CONNECTOR-TRACKER.md)** records which, how",
        "many, and how many this index carries.",
        "",
        "Intuit's `quickbooks-claude-plugin` is the notable one: a ledger vendor shipping",
        "its own bookkeeping skills, Apache-2.0. Square, Xero, Google Ads, Meta and Klaviyo",
        "publish none at the time of writing.",
        "",
        "---",
        "",
        "## How this repository works",
        "",
        "```",
        "data/sources/<system>/   one folder per data source, one file per skill",
        "data/meta.yml            stages and index-wide settings",
        "connectors.yml           reachability and vendor tracking, one file",
        "scripts/build.py         regenerates README.md and skills/*/README.md",
        "scripts/check_drift.py   compares each pointer against upstream, daily in CI",
        "docs/TRUST-TIERS.md      what every badge means",
        "skills/<id>/README.md    generated — purpose, inputs, outputs, limits",
        "connectors/<id>/README.md generated — reachability, vendor skills, what runs on it",
        "```",
        "",
        "```bash",
        "make setup                                    # once",
        "make add URL=<github url of a skill> STAGE=6  # add an entry, baseline it, rebuild",
        "make drift                                    # re-check every pointer",
        "make build                                    # regenerate the docs",
        "```",
        "",
        "`make add` reads the upstream `SKILL.md` frontmatter and the repository licence,",
        "writes a correctly-shaped `UNGRADED` entry, records its drift baseline, and rebuilds.",
        "It never assigns a trust tier — that is the one step a person has to do.",
        "",
        "## Licensing and why nothing is vendored",
        "",
        "`anthropics/skills` ships a per-skill `LICENSE.txt` reading *\"© 2025 Anthropic, PBC.",
        "All rights reserved\"*, with use governed by your own Anthropic agreement. That is not",
        "an open-source licence, so those skills are **pointed at, never copied**. CI fails any",
        "pull request that adds files under a pointer whose licence is not permissive.",
        "",
        "The published Mosofin skills are AGPL-3.0 — open source, but strong copyleft. They are",
        "pointed at rather than vendored, because mirroring them would relicense this index.",
        "That is a decision to take on purpose, not by default.",
        "",
        "Entries carrying a permissive licence (MIT, Apache-2.0) may set `mirror: true` and be",
        "vendored under `vendor/`, with attribution generated into `THIRD_PARTY_NOTICES.md`.",
        "",
        "## Contributing",
        "",
        "See [CONTRIBUTING.md](CONTRIBUTING.md). Adding an entry means adding one file under",
        "the data source it reads, then running the build — never editing a generated file.",
        "",
    ]
    return "\n".join(L)


def main() -> int:
    data = load_index()
    conn_meta = yaml.safe_load(CONNECTORS.read_text())
    meta = {
        **data["meta"],
        "stages": data["stages"],
        "connectors": conn_meta["connectors"],
        "statuses": conn_meta["statuses"],
    }

    unknown = {
        sys_
        for s in data["skills"]
        for sys_ in (s.get("systems") or [])
        if sys_ not in conn_meta["connectors"]
    }
    if unknown:
        print(f"systems with no entry in connectors.yml: {sorted(unknown)}", file=sys.stderr)
        return 1
    ids = [s["id"] for s in data["skills"]]
    if len(ids) != len(set(ids)):
        dupes = {i for i in ids if ids.count(i) > 1}
        print(f"duplicate skill ids: {sorted(dupes)}", file=sys.stderr)
        return 1

    (ROOT / "README.md").write_text(index_page(data, conn_meta))
    (ROOT / "docs" / "CONNECTOR-TRACKER.md").write_text(tracker_page(conn_meta))

    (ROOT / "connectors").mkdir(exist_ok=True)
    (ROOT / "connectors" / "README.md").write_text(
        connectors_index(conn_meta, data["skills"])
    )
    n_conn = 0
    for cid, c in conn_meta["connectors"].items():
        if cid in NOT_A_SOURCE:
            continue
        d = ROOT / "connectors" / cid
        d.mkdir(parents=True, exist_ok=True)
        (d / "README.md").write_text(
            connector_page(cid, c, conn_meta, data["skills"], meta["stages"])
        )
        n_conn += 1
    for skill in data["skills"]:
        d = ROOT / "skills" / skill["id"]
        d.mkdir(parents=True, exist_ok=True)
        (d / "README.md").write_text(skill_page(skill, meta))

    print(f"built README.md, {len(data['skills'])} skill pages, {n_conn} connector pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
