#!/usr/bin/env python3
"""Regenerate README.md and skills/<id>/README.md from sources.yml.

Everything this writes is derived. Edit sources.yml, then run:
    ./.venv/bin/python scripts/build.py
"""
from __future__ import annotations

import datetime as dt
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCES = ROOT / "sources.yml"
CONNECTORS = ROOT / "connectors.yml"
def esc(v) -> str:
    """Escape angle brackets so placeholders like <YYYY-MM> survive Markdown."""
    return str(v).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


GENERATED = "<!-- GENERATED BY scripts/build.py — DO NOT EDIT. Edit sources.yml instead. -->"

AUTHORITY_LABEL = {
    "first-party": "**First-party** — published by the organisation that owns the product",
    "notable": "Notable — a widely-used author, but not the product owner",
    "community": "Community",
}

ORIGIN_LABEL = {
    "mosofin-workspace": "Mosofin workspace",
    "mosofin-published": "Mosofin published",
    "third-party": "Third party",
}

# Host capabilities a skill needs, inferred from its grading. See docs/TRUST-TIERS.md
# — these are stated inferences, not test results.
PERMISSIVE = {"mit", "apache-2.0", "bsd-3-clause", "bsd-2-clause", "isc", "cc0-1.0"}
COPYLEFT = {"agpl-3.0", "gpl-3.0", "gpl-2.0", "lgpl-3.0", "mpl-2.0"}

PLATFORMS = ["Claude Code", "Claude.ai", "Codex", "Cursor", "Gemini CLI", "Copilot"]
HOST_CAPS = {
    # platform: (runs scripts, persistent filesystem, MCP connectors)
    "Claude Code": (True, True, True),
    "Claude.ai": (True, False, True),
    "Codex": (True, True, False),
    "Cursor": (True, True, True),
    "Gemini CLI": (True, True, False),
    "Copilot": (False, False, False),
}


def needs(skill: dict) -> tuple[bool, bool, bool]:
    """(code execution, persistent filesystem, connector) — derived from grading."""
    tiers = set(skill.get("tiers") or [])
    inputs = skill.get("inputs") or []
    outputs = skill.get("outputs") or []
    code = bool(tiers & {"DETERMINISTIC-MATH", "TIE-CHECKED"})
    fs = bool(tiers & {"AUDIT-TRAIL", "STATEFUL", "POLICY-CAPTURING"}) or any(
        "workspace" in str(o.get("dest", "")) or "closes/" in str(o.get("dest", ""))
        for o in outputs
    )
    conn = any("integration manifest" in str(i.get("source", "")) for i in inputs)
    return code, fs, conn


def compat_row(skill: dict) -> str:
    if skill.get("status") == "UNGRADED":
        return " | ".join("?" for _ in PLATFORMS)
    n_code, n_fs, n_conn = needs(skill)
    cells = []
    for p in PLATFORMS:
        h_code, h_fs, h_conn = HOST_CAPS[p]
        missing = []
        if n_code and not h_code:
            missing.append("no scripts")
        if n_fs and not h_fs:
            missing.append("no workspace")
        if n_conn and not h_conn:
            missing.append("supply exports")
        cells.append("full" if not missing else "partial — " + ", ".join(missing))
    return " | ".join(cells)


def badges(skill: dict) -> str:
    out = [f"`{skill['status']}`"]
    out += [f"`{t}`" for t in (skill.get("tiers") or [])]
    return " ".join(out)


def is_stale(skill: dict, days: int) -> bool:
    lg = skill.get("last_graded")
    if not lg:
        return False
    return (dt.date.today() - dt.date.fromisoformat(str(lg))).days > days


def upstream_str(skill: dict) -> str:
    up = skill.get("upstream") or {}
    if "repo" in up:
        return (
            f"[`{up['repo']}/{up['path']}`]"
            f"(https://github.com/{up['repo']}/tree/{up.get('ref', 'main')}/{up['path']})"
        )
    return f"`{up.get('local', 'unknown')}` (local)"


def skill_page(skill: dict, meta: dict) -> str:
    L = [GENERATED, "", f"# {skill['title']}", "", badges(skill), "", skill["summary"].strip(), ""]

    L += ["| | |", "|---|---|"]
    L += [f"| Origin | {ORIGIN_LABEL.get(skill['origin'], skill['origin'])} |"]
    L += [f"| Authority | {AUTHORITY_LABEL.get(skill.get('authority', 'community'))} |"]
    L += [f"| Stage | {skill['stage']} — {meta['stages'][skill['stage']]['name']} |"]
    L += [f"| Systems | {', '.join(skill.get('systems') or ['—'])} |"]
    L += [f"| Source | {upstream_str(skill)} |"]
    L += [f"| License | `{skill.get('license', 'unknown')}` |"]
    L += [f"| Mirrored here | {'yes' if skill.get('mirror') else 'no — pointer only'} |"]
    if skill.get("last_graded"):
        L += [f"| Last graded | {skill['last_graded']} |"]
    L += [""]

    if skill.get("status") == "UNGRADED":
        L += [
            "> **Not yet graded.** This entry is listed and pointed at, but nobody has read",
            "> its source line-by-line and assigned trust tiers. Treat the absence of badges",
            "> as *unknown*, not as *passing*. Inputs and outputs below are unverified.",
            "",
        ]

    if skill.get("tier_notes"):
        L += ["## Why these badges", ""]
        for tier, note in skill["tier_notes"].items():
            L += [f"- **`{tier}`** — {esc(note)}"]
        L += [""]

    if skill.get("inputs"):
        L += ["## Inputs", "", "| Input | Required | Where it comes from | If it's missing |", "|---|---|---|---|"]
        for i in skill["inputs"]:
            req = "**yes**" if i.get("required") else "no"
            L += [f"| `{esc(i['name'])}` | {req} | {esc(i.get('source', '—'))} | {esc(i.get('fallback', '—'))} |"]
        L += [""]

    if skill.get("outputs"):
        L += ["## Outputs", "", "| Output | Type | Where it lands |", "|---|---|---|"]
        for o in skill["outputs"]:
            L += [f"| {esc(o['name'])} | {esc(o.get('type', '—'))} | {esc(o.get('dest', '—'))} |"]
        L += [""]

    if skill.get("never"):
        L += ["## What it will not do", ""]
        L += [f"- {esc(n)}" for n in skill["never"]]
        L += [""]

    conn = meta.get("connectors", {})
    cstat = meta.get("statuses", {})
    rows = [(sys_, conn.get(sys_, {})) for sys_ in (skill.get("systems") or [])]
    if rows:
        L += ["## Data reachability", "", "| System | Status | Auth | Settlement data |", "|---|---|---|---|"]
        for name, c in rows:
            st = c.get("status", "unknown")
            L += [
                f"| `{name}` | **{st}** — {cstat.get(st, '')} | `{c.get('auth', '—')}` "
                f"| {c.get('payouts', '—')} |"
            ]
        L += [""]
        blocked = [n for n, c in rows if c.get("status") in {"gated", "declined"}]
        costly = [n for n, c in rows if c.get("status") == "hard"]
        if blocked:
            L += [f"> **Not reachable.** {', '.join(blocked)} — the grading above is academic until that changes.", ""]
        elif costly:
            L += [f"> **Reachable at cost.** {', '.join(costly)} needs per-merchant credentials or a plan upgrade.", ""]
        notes = [f"- `{n}` — {c['note']}" for n, c in rows if c.get("note")]
        if notes:
            L += notes + [""]

    L += ["## Host compatibility", ""]
    L += ["| " + " | ".join(PLATFORMS) + " |", "|" + "---|" * len(PLATFORMS)]
    L += ["| " + compat_row(skill) + " |", ""]
    if skill.get("status") != "UNGRADED":
        n_code, n_fs, n_conn = needs(skill)
        req = [
            x
            for x, on in (
                ("script execution", n_code),
                ("a persistent workspace", n_fs),
                ("a live data connector", n_conn),
            )
            if on
        ]
        L += [f"Requires from the host: {', '.join(req) if req else 'nothing beyond reading instructions'}.", ""]
    L += [
        "*Inferred from the skill's grading, not from running it on each platform —"
        " see [Platform compatibility](../../docs/TRUST-TIERS.md#platform-compatibility).*",
        "",
        "---",
        "",
        "[← back to the index](../../README.md) · [trust tiers](../../docs/TRUST-TIERS.md)",
        "",
    ]
    return "\n".join(L)


STATUS_ORDER = [
    "live", "code-complete", "roadmap", "candidate",
    "costly", "gated", "not-recommended", "declined", "local",
]


def connector_section(conn: dict) -> list[str]:
    """The candidate list, grouped by how committed each connector is."""
    cs, out = conn["statuses"], []
    by_status: dict[str, list] = {}
    for name, c in conn["connectors"].items():
        by_status.setdefault(c.get("status", "candidate"), []).append((name, c))

    for status in STATUS_ORDER:
        rows = sorted(by_status.get(status, []))
        if not rows or status == "local":
            continue
        out += [
            f"#### {status} — {cs.get(status, '')}",
            "",
            "| Connector | Family | Auth | Entity | Token | Settlement | Lead time |",
            "|---|---|---|---|---|---|---|",
        ]
        for name, c in rows:
            key = c.get("connector_key")
            label = f"`{name}`" + (f"<br><sub>`{key}`</sub>" if key else "")
            out.append(
                f"| {label} | {c.get('family', '—')} | `{c.get('auth', '—')}` "
                f"| {esc(c.get('entity', '—'))} | {esc(c.get('token', '—'))} "
                f"| {c.get('payouts', '—')} | {esc(c.get('lead_time', '—'))} |"
            )
        out.append("")
        notes = [(n, c["note"]) for n, c in rows if c.get("note")]
        for n, note in notes:
            out.append(f"- **`{n}`** — {esc(' '.join(note.split()))}")
        if notes:
            out.append("")
    return out


def publisher_rows(skills: list) -> list[str]:
    """One row per upstream publisher, so provenance is visible at a glance."""
    groups: dict[str, dict] = {}
    for s in skills:
        up = s.get("upstream") or {}
        key = up.get("repo") or "Mosofin (local workspace)"
        g = groups.setdefault(key, {"n": 0, "auth": set(), "lic": set()})
        g["n"] += 1
        g["auth"].add(s.get("authority", "community"))
        g["lic"].add(str(s.get("license", "unknown")))

    rows = []
    for repo, g in sorted(groups.items(), key=lambda kv: (-kv[1]["n"], kv[0])):
        name = (
            f"[`{repo}`](https://github.com/{repo})" if "/" in repo and " " not in repo else repo
        )
        lic = ", ".join(sorted(g["lic"]))
        vendorable = (
            "yes"
            if all(l in PERMISSIVE for l in g["lic"])
            else ("no — copyleft" if any(l in COPYLEFT for l in g["lic"]) else "no — restricted")
        )
        rows.append(
            f"| {name} | {g['n']} | {', '.join(sorted(g['auth']))} | `{lic}` | {vendorable} |"
        )
    return rows


def index_page(data: dict, conn_meta: dict) -> str:
    meta = {**data["meta"], "stages": data["stages"]}
    skills = data["skills"]
    graded = [s for s in skills if s["status"] == "GRADED"]
    stale = [s for s in graded if is_stale(s, meta["regrade_after_days"])]
    regrade = [s for s in skills if s["status"] == "NEEDS-RE-GRADING"]
    # Derived from the data, never from wall-clock time: generated output must be
    # byte-identical on any day sources.yml has not changed, or CI's sync check
    # fails every day after the commit that produced it.
    checks = [str(s["last_checked"]) for s in skills if s.get("last_checked")]
    checked = max(checks) if checks else ""

    L = [GENERATED, "", f"# {meta['title']}", "", meta["tagline"], ""]
    L += [
        f"**{len(skills)} skills** · **{len(graded)} graded** · "
        f"**{len(skills) - len(graded)} awaiting grading** · "
        f"**{len(regrade)} need re-grading** · **{len(stale)} stale**"
        + (f" · pointers last checked {checked}" if checked else ""),
        "",
        "Every entry is graded for what happens when it is wrong: whether it can write to",
        "your ledger, whether its numbers are computed or asserted, whether it ends in a",
        "proof, and whether anything it produces can leave the building on its own.",
        "",
        "Other skill directories grade nothing. A skill that silently posts journal entries",
        "and one that proposes them look identical in a bullet list. In accounting they are",
        "not the same product.",
        "",
        "**[Read the trust tiers →](docs/TRUST-TIERS.md)**",
        "",
        "Nothing here is mirrored. Every third-party entry is a pointer to its own",
        "repository, checked daily; when an upstream `SKILL.md` changes, its grade is",
        "marked stale and a human re-reads it. The list is cheap — the grade is the product.",
        "",
        "---",
        "",
        "## The index",
        "",
        "Ordered by when you need it, not alphabetically.",
        "",
    ]

    for stage_no in sorted(meta["stages"]):
        stage = meta["stages"][stage_no]
        rows = [s for s in skills if s["stage"] == stage_no]
        if not rows:
            continue
        L += [f"### {stage_no} · {stage['name']}", "", f"*{stage['note']}*", ""]
        for s in sorted(rows, key=lambda x: (x["status"] != "GRADED", x["id"])):
            L += [
                f"- **[{s['title']}](skills/{s['id']}/README.md)** — "
                f"{ORIGIN_LABEL.get(s['origin'], s['origin'])}  "
            ]
            L += [f"  {badges(s)}  "]
            L += [f"  {' '.join(s['summary'].split())}"]
        L += [""]

    L += [
        "---",
        "",
        "## Connector pipeline",
        "",
        "A grade says what a skill does when it runs. This says whether it can run at all.",
        "A perfectly graded reconciliation skill is inert when its ledger sits behind a",
        "partner gate, so reachability is stated beside the grade rather than left for the",
        "reader to discover.",
        "",
        *connector_section(conn_meta),
        f"Sources: [{conn_meta['meta']['sources']['runbook']['title']}]"
        f"({conn_meta['meta']['sources']['runbook']['url']}) "
        f"(verified {conn_meta['meta']['sources']['runbook']['verified']}) — the committed",
        "roadmap, with connector keys, entities and token strategies; and",
        f"[{conn_meta['meta']['sources']['survey']['title']}]"
        f"({conn_meta['meta']['sources']['survey']['url']}) "
        f"(researched {conn_meta['meta']['sources']['survey']['verified']}) — the evaluated",
        "pool. " + " ".join(conn_meta["meta"]["caveat"].split()),
        "",
        "Three facts from that survey shape this index more than any other:",
        "",
        "- **Who issues the credential decides everything.** Three-legged OAuth is a",
        "  connector; merchant-generated keys are a support burden; a partner agreement is",
        "  business development. Nothing about the API surface changes that ordering.",
        "- **An API without settlement data cannot close the books.** Reconciliation needs",
        "  payouts, not just sales.",
        "- **The processor is the escape hatch — except in field service**, where embedded",
        "  payments mean the platform API is the only path to the money.",
        "",
        "---",
        "",
        "## Publishers",
        "",
        "Who stands behind each entry. **First-party** means the organisation that owns the",
        "product published the skill itself — the standing `anthropics/skills` has for Claude.",
        "It is a statement about provenance, not about quality, and it is never a substitute",
        "for a grade.",
        "",
        "| Publisher | Entries | Authority | Licence | Vendorable |",
        "|---|---|---|---|---|",
        *publisher_rows(skills),
        "",
        "No accounting or bookkeeping vendor — Intuit, Xero, Plaid, Ramp, Brex, Square,",
        "PayPal — publishes first-party agent skills at the time of writing. The finance",
        "vertical has no official publisher yet. That is the gap this index exists to fill.",
        "",
        "---",
        "",
        "## How this repository works",
        "",
        "```",
        "sources.yml              the only file you edit by hand",
        "scripts/build.py         regenerates README.md and skills/*/README.md",
        "scripts/check_drift.py   compares each pointer against upstream, daily in CI",
        "docs/TRUST-TIERS.md      what every badge means",
        "skills/<id>/README.md    generated — purpose, inputs, outputs, limits",
        "```",
        "",
        "```bash",
        "make setup                                    # once",
        "make add URL=<github url of a skill> STAGE=6  # add an entry, baseline it, rebuild",
        "make drift                                    # re-check every pointer",
        "make build                                    # regenerate the docs",
        "```",
        "",
        "`make add` reads the upstream `SKILL.md` frontmatter and the repository licence,",
        "writes a correctly-shaped `UNGRADED` entry, records its drift baseline, and rebuilds.",
        "It never assigns a trust tier — that is the one step a person has to do.",
        "",
        "## Licensing and why nothing is vendored",
        "",
        "`anthropics/skills` ships a per-skill `LICENSE.txt` reading *\"© 2025 Anthropic, PBC.",
        "All rights reserved\"*, with use governed by your own Anthropic agreement. That is not",
        "an open-source licence, so those skills are **pointed at, never copied**. CI fails any",
        "pull request that adds files under a pointer whose licence is not permissive.",
        "",
        "The published Mosofin skills are AGPL-3.0 — open source, but strong copyleft. They are",
        "pointed at rather than vendored, because mirroring them would relicense this index.",
        "That is a decision to take on purpose, not by default.",
        "",
        "Entries carrying a permissive licence (MIT, Apache-2.0) may set `mirror: true` and be",
        "vendored under `vendor/`, with attribution generated into `THIRD_PARTY_NOTICES.md`.",
        "",
        "## Contributing",
        "",
        "See [CONTRIBUTING.md](CONTRIBUTING.md). Adding an entry means adding a block to",
        "`sources.yml` and running the build — never editing a generated file.",
        "",
    ]
    return "\n".join(L)


def main() -> int:
    data = yaml.safe_load(SOURCES.read_text())
    conn_meta = yaml.safe_load(CONNECTORS.read_text())
    meta = {
        **data["meta"],
        "stages": data["stages"],
        "connectors": conn_meta["connectors"],
        "statuses": conn_meta["statuses"],
    }

    unknown = {
        sys_
        for s in data["skills"]
        for sys_ in (s.get("systems") or [])
        if sys_ not in conn_meta["connectors"]
    }
    if unknown:
        print(f"systems with no entry in connectors.yml: {sorted(unknown)}", file=sys.stderr)
        return 1
    ids = [s["id"] for s in data["skills"]]
    if len(ids) != len(set(ids)):
        dupes = {i for i in ids if ids.count(i) > 1}
        print(f"duplicate ids in sources.yml: {sorted(dupes)}", file=sys.stderr)
        return 1

    (ROOT / "README.md").write_text(index_page(data, conn_meta))
    for skill in data["skills"]:
        d = ROOT / "skills" / skill["id"]
        d.mkdir(parents=True, exist_ok=True)
        (d / "README.md").write_text(skill_page(skill, meta))

    print(f"built README.md and {len(data['skills'])} skill pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
