#!/usr/bin/env python3
"""Generate the Claude plugin's reference files from the index.

The plugin is the directory-publishable face of this repository. It ships one
read-only skill, `finance-ops-skills`, plus a generated reference file per vendor.
Nothing from a vendor is copied: each entry is a pointer to the upstream skill.

Called from build.py. Everything under plugins/<name>/skills/*/references/ and the
plugin README is derived, as is the `version` field of plugin.json. The rest of
plugin.json, the SKILL.md, LICENSE and evals/ are hand-written.

Versioning follows the Claude Code docs: a user receives a new copy of a plugin only
when its version string changes, and the version is set in plugin.json alone, never
also in the marketplace entry. The catalog is the plugin's content, so the version's
patch number is the date of the newest catalog fact. It is derived from the data, not
the clock, so the build stays byte-identical on days nothing changed.
"""
from __future__ import annotations

import json
import pathlib
import shutil

PLUGIN = "finance-ops-skills-index"
VERSION_BASE = "1.0"  # raise by hand when the skill or the reference format changes
SKIP_STATUS = {"local"}
GENERATED = "<!-- GENERATED BY scripts/build_plugin.py — DO NOT EDIT. Edit data/ and connectors.yml. -->"


def _link(skill: dict) -> str:
    up = skill.get("upstream") or {}
    if "repo" not in up:
        return f"`{up.get('local', 'unknown')}` (local)"
    return f"https://github.com/{up['repo']}/tree/{up.get('ref', 'main')}/{up['path']}"


def _vendor_page(cid: str, c: dict, skills: list, statuses: dict) -> str:
    repo = c.get("skills_repo", "none")
    L = [GENERATED, "", f"# {cid}", ""]
    L.append(f"- Reachability: **{c['status']}** — {statuses.get(c['status'], '')}")
    L.append(f"- Vertical: {c.get('vertical', 'n/a')}")
    if repo and repo != "none":
        L.append(f"- Vendor skills repository: https://github.com/{repo}")
        L.append(
            f"- Published there: {c.get('skills_published', 0)} · "
            f"indexed here: {len(skills)} · checked {c.get('skills_checked', 'n/a')}"
        )
        if c.get("skills_license"):
            L.append(f"- Repository licence: {c['skills_license']}")
    else:
        L.append(
            f"- **No vendor-published skills found** as of {c.get('skills_checked', 'the last check')}."
        )
    if c.get("skills_note"):
        L.append(f"- Note: {' '.join(str(c['skills_note']).split())}")
    L += ["", "## Indexed skills", ""]
    if not skills:
        L.append("None indexed. Do not invent one — say so and point to the vendor's own developer docs.")
    for s in sorted(skills, key=lambda x: x["id"]):
        L += [
            f"### {s['id']}",
            "",
            f"- Authority: {s.get('authority', 'community')} · stage {s.get('stage', 'n/a')} · "
            f"status {s.get('status', 'UNGRADED')}"
            + (f" (graded {s['last_graded']})" if s.get("last_graded") else ""),
            f"- Trust badges: {', '.join(s.get('tiers') or []) or 'none'}",
            *[f"  - {b}: {' '.join(str(n).split())}" for b, n in (s.get("tier_notes") or {}).items()],
            f"- Licence: {s.get('license', 'unknown')}",
            f"- Upstream: {_link(s)}",
            f"- Summary: {' '.join(str(s.get('summary', '')).split())}",
        ]
        if s.get("never"):
            L.append("- Never: " + " | ".join(str(n) for n in s["never"]))
        L.append("")
    return "\n".join(L)


def build(root: pathlib.Path, skills: list, connectors: dict, statuses: dict, primary_system) -> int:
    pdir = root / "plugins" / PLUGIN
    ref = pdir / "skills" / "finance-ops-skills" / "references"
    if ref.exists():
        shutil.rmtree(ref)
    ref.mkdir(parents=True)

    by_system: dict[str, list] = {}
    for s in skills:
        by_system.setdefault(primary_system(s), []).append(s)

    rows, n = [], 0
    for cid, c in connectors.items():
        if c.get("status") in SKIP_STATUS:
            continue
        mine = by_system.get(cid, [])
        (ref / f"{cid}.md").write_text(_vendor_page(cid, c, mine, statuses))
        repo = c.get("skills_repo", "none")
        rows.append(
            f"| {cid} | {c.get('vertical', '')} | {c['status']} | "
            f"{'none' if repo in (None, 'none') else repo} | {len(mine)} |"
        )
        n += 1

    anyskills = by_system.get("_any", [])
    (ref / "_any.md").write_text(
        _vendor_page("_any (no connected system)", {"status": "local", "vertical": "files"}, anyskills, statuses)
    )

    (ref / "INDEX.md").write_text(
        "\n".join(
            [GENERATED, "", "# Vendors in this index", "",
             "| Vendor | Vertical | Reachability | Vendor skills repo | Indexed |",
             "| - | - | - | - | - |", *rows,
             f"| _any | files | local | — | {len(anyskills)} |", ""]
        )
    )

    dates = [str(s.get(k)) for s in skills for k in ("last_checked", "last_graded") if s.get(k)]
    dates += [str(c["skills_checked"]) for c in connectors.values() if c.get("skills_checked")]
    newest = max(dates)
    manifest = pdir / ".claude-plugin" / "plugin.json"
    pj = json.loads(manifest.read_text())
    pj["version"] = f"{VERSION_BASE}.{newest.replace('-', '')}"
    manifest.write_text(json.dumps(pj, indent=2, ensure_ascii=False) + "\n")

    vendors = sorted(cid for cid, c in connectors.items() if c.get("status") not in SKIP_STATUS)
    (pdir / "README.md").write_text(
        "\n".join(
            [
                GENERATED, "",
                "# Finance & Ops Skills Index", "",
                "Find the agent skills that software vendors publish for their own finance and "
                "business-operations products — accounting, payments, e-commerce, CRM — and see "
                "how far each can be trusted before you install it.", "",
                "## What it does", "",
                "The plugin adds one skill, `finance-ops-skills`. Claude uses it when you ask "
                "whether skills exist for a platform, which one fits a task, or whether one is safe "
                "to use. It answers from a catalog bundled in the plugin: for each skill, the "
                "upstream link, who published it (the vendor itself, or a third party), its licence, "
                "and an independent grade — can it write to your books, can it move money, does it "
                "send your prompts to the vendor. Vendors with nothing published are listed as such "
                "rather than left out.", "",
                f"Catalog as of **{newest}** · {len(skills)} skills · {len(vendors)} vendors.", "",
                "## How to use it", "",
                "Install it, then ask in plain language:", "",
                "- \"Are there any official skills for Xero?\"",
                "- \"Which QuickBooks skills can post journal entries?\"",
                "- \"Is there a Stripe skill that moves money, and does it ask first?\"",
                "- \"What should I use to reconcile Shopify payouts?\"", "",
                "In Claude Code:", "",
                "```",
                "/plugin marketplace add MosoFin/finance-ops-skills-index",
                f"/plugin install {PLUGIN}@{PLUGIN}",
                "```", "",
                "On claude.ai and in Cowork, add it from **Customize > Plugins**.", "",
                "The plugin never installs a vendor skill for you. Follow the upstream link it "
                "gives you and install from the vendor.", "",
                "## Data", "",
                "The plugin sends nothing anywhere. It has no MCP server, no hooks and no scripts, "
                "makes no network calls and holds no credentials; it reads only its own bundled "
                "Markdown files. The vendor skills it points to are separate software with their "
                "own data practices, which the catalog notes where they send telemetry.", "",
                "## Coverage", "",
                ", ".join(vendors) + ".", "",
                "The full table is in `skills/finance-ops-skills/references/INDEX.md`.", "",
                "## Source and licence", "",
                "Generated from the data files in "
                "[MosoFin/finance-ops-skills-index](https://github.com/MosoFin/finance-ops-skills-index), "
                "which re-checks every upstream pointer daily. MIT licensed; see `LICENSE`. The "
                "vendor skills it lists are licensed by their publishers.", "",
            ]
        )
    )
    return n
